- rubocop-minitest.gemspec
This PR fixes the following CI error.
```console
$ #!/bin/bash -eo pipefail
bundle install
The git source `git://github.com/rubocop-hq/rubocop.git` uses the `git`
protocol, which transmits data without encryption. Disable this warning
with `bundle config git.allow_insecure true`, or switch to the `https`
protocol to keep your data secure.
Fetching git://github.com/rubocop-hq/rubocop.git
Fetching gem metadata from https://rubygems.org/.............
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Bundler could not find compatible versions for gem "bundler":
In Gemfile:
bundler (~> 2.0)
Current Bundler version:
bundler (1.17.3)
This Gemfile requires a different version of Bundler.
Perhaps you need to update Bundler by running `gem install bundler`?
Could not find …
```
> Fix an error on CircleCI

- README.md
This commit adds a basic instruction on how to use the cops in the
README file.
> Include basic instructions on how to use in README

- CHANGELOG.md
- config/default.yml
- lib/rubocop/cop/minitest/refute_nil.rb
- lib/rubocop/cop/minitest_cops.rb
- manual/cops.md
- manual/cops_minitest.md
- test/rubocop/cop/minitest/refute_nil_test.rb
> Add new cop `Minitest/RefuteNil`

- CHANGELOG.md
- config/default.yml
- lib/rubocop/cop/minitest/assert_truthy.rb
- lib/rubocop/cop/minitest_cops.rb
- manual/cops.md
- manual/cops_minitest.md
- test/rubocop/cop/minitest/assert_truthy_test.rb
PR adds cops to enforce use of `assert` over `assert_equal(true, actual)`. 
Ref: https://github.com/rubocop-hq/minitest-style-guide#assert-truthy
> Added cop to enforce assert truthy over assert_equal(true, actual)

- CHANGELOG.md
- config/default.yml
- lib/rubocop/cop/minitest/assert_includes.rb
- lib/rubocop/cop/minitest_cops.rb
- manual/cops.md
- manual/cops_minitest.md
- test/rubocop/cop/minitest/assert_includes_test.rb
PR adds cops to enforce the use of `assert_includes` over `assert(collection.includes?(actual))`
Ref: https://github.com/rubocop-hq/minitest-style-guide#assert-includes
> Added a cop to enforce assert_includes over assert(collection.includes?(actual))

- CHANGELOG.md
- config/default.yml
- lib/rubocop/cop/minitest/assert_empty.rb
- lib/rubocop/cop/minitest_cops.rb
- manual/cops.md
- manual/cops_minitest.md
- test/rubocop/cop/minitest/assert_empty_test.rb
PR adds cops to enforce the use of `assert_empty` over `assert(actual.empty?)`
Ref: https://github.com/rubocop-hq/minitest-style-guide#assert-empty
> Added a cop to enforce assert_empty over assert(actual.empty?)

- CHANGELOG.md
- config/default.yml
Fixes #13.
This PR fixes an issue that all cops only executed test directory.
Only test directory should be executed by Minitest department.
> [Fix #13] Fix the execution target specified in `Include` parameter

- test/rubocop/cop/minitest/assert_includes_test.rb
Assert Include cop test description had a typo. Changed it from `assert_nil` -> `assert_includes`
> Fixed the test description typo from assert_nil -> assert_includes

- CHANGELOG.md
- config/default.yml
- lib/rubocop/cop/minitest/assert_includes.rb
- manual/cops_minitest.md
- test/rubocop/cop/minitest/assert_includes_test.rb
This PR fixes the typo for AssertIncludes cop. Changes `collection.includes` -> `collection.include` at all places.
> Fixed typo for AssertIncludes cop. Changed includes -> include

- test/rubocop/cop/minitest/assert_empty_test.rb
- test/rubocop/cop/minitest/assert_includes_test.rb
- test/rubocop/cop/minitest/assert_nil_test.rb
- test/rubocop/cop/minitest/assert_truthy_test.rb
- test/rubocop/cop/minitest/refute_nil_test.rb
This PR removes the redundant test cases added for constant and variables message argument test cases for all the assertion. 
Refer the comment by @bbatsov for more details: https://github.com/rubocop-hq/rubocop-minitest/pull/20#discussion_r331735949
> Removed redundant test cases added for checking constant and variables messages to an assertion

- config/default.yml
- lib/rubocop/cop/minitest/assert_empty.rb
- lib/rubocop/cop/minitest/assert_includes.rb
- manual/cops_minitest.md
- test/rubocop/cop/minitest/assert_includes_test.rb
As per @bbatsov comment, renamed the argument where no expectation is present to `object` from `actual`. 
Ref: https://github.com/rubocop-hq/rubocop-minitest/pull/20#discussion_r331858962
> Renamed the assertion argument to object from actual

- lib/rubocop/cop/minitest/refute_equal.rb
- lib/rubocop/cop/minitest/refute_false.rb
- manual/cops_minitest.md
Hey folks 👋
I think we have a english typo in refute_equal and refute_false class
documentation. Instead of `enforces the usages` it should be `enforces
the use`.
> Fix English typo in the class documentation

- CHANGELOG.md
- config/default.yml
- lib/rubocop/cop/minitest/assert_respond_to.rb
- lib/rubocop/cop/minitest_cops.rb
- manual/cops.md
- manual/cops_minitest.md
- test/rubocop/cop/minitest/assert_respond_to_test.rb
This commit adds a cop that checks the usage of
`assert(object.respond_to?(:some_method))` and enforces the usage of
`assert_respond_to(object, :some_method)` instead.
> Include a cop to enforce assert_respond_to

- Gemfile
- relnotes/v0.1.0.md
- relnotes/v0.2.0.md
- relnotes/v0.2.1.md
- relnotes/v0.3.0.md
- tasks/cut_release.rake
This PR adds the following rake tasks.
```console
% rake -T | grep cut_release
rake cut_release:major                    # Cut a new major release,
create release notes and update documents
rake cut_release:minor                    # Cut a new minor release,
create release notes and update documents
rake cut_release:patch                    # Cut a new patch release,
create release notes and update documents
rake cut_release:pre                      # Cut a new pre release,
create release notes and update documents
```
And the release notes from v0.1.0 to v0.3.0 already released will be added.
> Add release task and release notes

- lib/rubocop/cop/minitest/refute_equal.rb
- manual/cops_minitest.md
> Typo fix in documentation of refute_equal

- CHANGELOG.md
- config/default.yml
Fixes #25.
This PR adds `Enabled: true` to `Minitest` department config.
It resolves the following warning:
```yaml
require: rubocop-minitest
AllCops:
DisabledByDefault: true
Minitest:
Enabled: true
```
```console
% bundle exec rubocop
Warning: Minitest does not support Enabled parameter.
Supported parameters are:
- Include
```
> [Fix #25] Add `Enabled: true` to `Minitest` department config

- CHANGELOG.md
- lib/rubocop/cop/minitest/assert_respond_to.rb
- lib/rubocop/cop/minitest/refute_respond_to.rb
- manual/cops_minitest.md
- test/rubocop/cop/minitest/assert_respond_to_test.rb
- test/rubocop/cop/minitest/refute_respond_to_test.rb
Fixes #39.
This PR fixes an incorrect autocorrect for `Minitest/AssertRespondTo` and `Minitest/RefuteRespondTo` when using assertion method calling `respond_to` with receiver omitted.
> [Fix #39] Fix an incorrect autocorrect for `Minitest/AssertRespondTo`

- Gemfile
This PR solves the following "The manual directory is out of sync" error when using Ruby 2.7.0-dev.
```console
% ruby -v
ruby 2.7.0dev (2019-12-03T05:51:14Z master e42d9d8df8) [x86_64-darwin17]
% CI=true bundle exec rake
(snip)
The manual directory is out of sync. Run `rake
generate_cops_documentation` and commit the results.
```
https://circleci.com/gh/rubocop-hq/rubocop-minitest/968
This issue will be resolved with the release of YARD 0.9.21 or higher, which includes the following changes:
https://github.com/lsegal/yard/pull/1290
> Workaround for broke CI with YARD 0.9.20 when using Ruby 2.7.0-dev

- Gemfile
This reverts commit f170cc5d74ff8f743f6de06c2a3fe0cf2af8dc57.
> Revert "Workaround for broke CI with YARD 0.9.20 when using Ruby 2.7.0-dev"

- lib/rubocop/minitest/inject.rb
Follow up of https://github.com/rubocop-hq/rubocop-extension-generator/pull/8.
> Enable to work `Exclude` in AllCops section

- test/project_test.rb
This PR adds a project tests for changelog format.
project_test.rb is based on RuboCop Performance's project_spec.rb.
https://github.com/rubocop-hq/rubocop-performance/blob/v1.5.2/spec/project_spec.rb
> Add a project tests for changelog format

- CHANGELOG.md
- lib/rubocop/cop/minitest/refute_false.rb
- manual/cops_minitest.md
- test/rubocop/cop/minitest/refute_false_test.rb
This PR makes `Minitest/RefuteFalse` cop aware of `assert(!test)`.
It solves one of the following issue #52.
https://github.com/rubocop-hq/rubocop-minitest/issues/52#issuecomment-584031108.
The issue #52 has another `Minitest/RefuteIncludes` cop's false negative, which will be resolved in another PR.
> Make `Minitest/RefuteFalse` cop aware of `assert(!test)`

- CHANGELOG.md
- lib/rubocop/cop/minitest/assert_includes.rb
- lib/rubocop/cop/minitest/refute_includes.rb
- lib/rubocop/cop/minitest_cops.rb
- lib/rubocop/cop/mixin/includes_cop_rule.rb
- test/rubocop/cop/minitest/assert_includes_test.rb
- test/rubocop/cop/minitest/refute_includes_test.rb
Fixes #52.
This PR fixes a false negative for `Minitest/AssertIncludes` and `Minitest/RefuteIncludes` when an argument is enclosed in redundant parentheses.
Probably will be corrected separately for similar false negatives that other cops will have.
> [Fix #52] Fix a false negative for `Minitest/RefuteIncludes`

- CHANGELOG.md
- lib/rubocop/cop/mixin/includes_cop_rule.rb
- test/rubocop/cop/minitest/assert_includes_test.rb
Fixes #55
This PR fixes an error for `Minitest/AssertIncludes` when using local variable argument.
> [Fix #55] Fix an error for `Minitest/AssertIncludes`

- CHANGELOG.md
- lib/rubocop/cop/minitest/assert_includes.rb
- lib/rubocop/cop/minitest/assert_match.rb
- lib/rubocop/cop/minitest/refute_includes.rb
- lib/rubocop/cop/minitest/refute_match.rb
- lib/rubocop/cop/minitest_cops.rb
- lib/rubocop/cop/mixin/minitest_cop_rule.rb
- test/rubocop/cop/minitest/assert_match_test.rb
- test/rubocop/cop/minitest/refute_match_test.rb
Follow #54.
This PR fixes a false negative for `Minitest/AssertMatch` and `Minitest/RefuteMatch` when an argument is enclosed in redundant parentheses.
> Fix a false negative for `Minitest/AssertMatch` and `Minitest/RefuteMatch`

- CHANGELOG.md
- lib/rubocop/cop/minitest/assert_respond_to.rb
- lib/rubocop/cop/minitest/refute_respond_to.rb
- lib/rubocop/cop/mixin/minitest_cop_rule.rb
- test/rubocop/cop/minitest/assert_respond_to_test.rb
- test/rubocop/cop/minitest/refute_respond_to_test.rb
Follow #54.
This PR fixes a false negative for `Minitest/AssertRespondTo` and `Minitest/RefuteRespondTo`
when an argument is enclosed in redundant parentheses.
> Fix a false negative for `Minitest/AssertRespondTo`

- CHANGELOG.md
- lib/rubocop/cop/minitest/assert_instance_of.rb
- lib/rubocop/cop/minitest/refute_instance_of.rb
- lib/rubocop/cop/mixin/minitest_cop_rule.rb
- test/rubocop/cop/minitest/assert_instance_of_test.rb
- test/rubocop/cop/minitest/refute_instance_of_test.rb
Follow #54.
Fix a false negative for `Minitest/AssertInstanceOf` and `Minitest/RefuteInstanceOf` when an argument is enclosed in redundant parentheses.
> Fix a false negative for `Minitest/AssertInstanceOf`

- CHANGELOG.md
- lib/rubocop/cop/minitest/assert_empty.rb
- lib/rubocop/cop/minitest/refute_empty.rb
- lib/rubocop/cop/mixin/minitest_cop_rule.rb
- test/rubocop/cop/minitest/assert_empty_test.rb
- test/rubocop/cop/minitest/refute_empty_test.rb
Follow #54.
This PR fixes a false negative for `Minitest/AssertEmpty` and `Minitest/RefuteEmpty` when an argument is enclosed in redundant parentheses.
> Fix a false negative for `Minitest/AssertEmpty`

- CHANGELOG.md
- lib/rubocop/cop/minitest/global_expectations.rb
- test/rubocop/cop/minitest/global_expectations_test.rb
Closes https://github.com/rubocop-hq/rubocop-minitest/issues/64
> [Fix #64] Fix `Minitest/GlobalExpectations` autocorrection for chained methods

- CHANGELOG.md
- lib/rubocop/cop/minitest/global_expectations.rb
Resolves #66.
This PR supports all expectations of `Minitest::Expectations` for `Minitest/GlobalExpectations` cop.
https://github.com/seattlerb/minitest/blob/v5.14.0/lib/minitest/expectations.rb
> [Fix #66] Support all expectations of `Minitest::Expectations`

- CHANGELOG.md
- lib/rubocop/cop/minitest/global_expectations.rb
- test/rubocop/cop/minitest/global_expectations_test.rb
Fix a false negative for `Minitest/GlobalExpectations` cop when using a variable or a hash index for receiver.
The following is a false nagative example.
```ruby
signed_url_params["Signature"].must_equal [Base64.strict_encode64("native-signature").delete("\n")]
```
> Fix a false negative for `Minitest/GlobalExpectations` cop

- lib/rubocop/cop/minitest/global_expectations.rb
- test/rubocop/cop/minitest/global_expectations_test.rb
This PR changes highlight area and offense message for `Minitest/GlobalExpectations` cop.
```console
% bundle exec rubocop --only Minitest/GlobalExpectations -a
(snip)
test/google/cloud/storage/bucket_compose_test.rb:59:5: C: [Corrected]
Minitest/GlobalExpectations: Prefer using _(new_file.name).must_equal
file_3_name.
new_file.name.must_equal file_3_name
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
```console
% bundle exec rubocop --only Minitest/GlobalExpectations -a
(snip)
test/google/cloud/storage/bucket_compose_test.rb:59:5: C: [Corrected]
Minitest/GlobalExpectations: Use _(new_file.name) instead.
new_file.name.must_equal file_3_name
^^^^^^^^^^^^^
```
This change will clarify an offense area.
and description …
> Change highlight area for `Minitest/GlobalExpectations`

- CHANGELOG.md
- lib/rubocop/cop/minitest/assert_equal.rb
- test/rubocop/cop/minitest/assert_equal_test.rb
Follow #54.
This PR fixes a false negative for `Minitest/AssertEqual` when an argument is enclosed in redundant parentheses.
> Fix a false negative for `Minitest/AssertEqual`

- .rubocop_todo.yml
- CHANGELOG.md
- lib/rubocop/cop/minitest/global_expectations.rb
- lib/rubocop/cop/mixin/minitest_cop_rule.rb
- test/assertion_helper.rb
- test/rubocop/cop/minitest/global_expectations_test.rb
Fixed some use cases for the `Minitest/GlobalExpectations` cop.
I have noticed there are cases when the cop doesn't produce offenses:
- expectation for constant e.g. class/module
- method call with arguments
- expectation for chained hash references
Let's look at some examples which the cope ignores:
```ruby
response[1]['X-Runtime'].must_match /[\d\.]+/
::File.read(::File.join(@def_disk_cache, 'path', 'to', 'blah.html')).must_equal @def_value.first
Rack::Contrib.must_respond_to(:release)
```
- https://github.com/rubocop-hq/rubocop-minitest/issues/60
- https://github.com/rubocop-hq/rubocop-minitest/pull/63
- https://github.com/rubocop-hq/rubocop-minitest/pull/69
and description in grammatically correct, …
> Fix some false negatives for `Minitest/GlobalExpectations`

- CHANGELOG.md
- config/default.yml
Fixes #73.
This PR changes the Minitest department works on file names end with `_test.rb` by default.
RuboCop Minitest only targets files in `test` directory by default until v0.8.1.
```yaml
Minitest:
Enabled: true
Include:
- '**/test/**/*'
```
https://github.com/rubocop-hq/rubocop-minitest/blob/v0.8.1/config/default.yml
But test files may be located in a directory other than `test` directory.
This PR adds files that end of filename is `_test.rb` to be considered test files.
This behavior is similar to how RuboCop RSpec works on `_spec.rb`.
https://github.com/rubocop-hq/rubocop-rspec/blob/v1.38.1/config/default.yml#L5
[1]: …
> [Fix #73] The Minitest department works on `_test.rb` by default

- CHANGELOG.md
- lib/rubocop/cop/minitest/global_expectations.rb
- test/rubocop/cop/minitest/global_expectations_test.rb
Fixes #75
This PR fixes a false negative for `Minitest/GlobalExpectations` when using global expectation methods with no arguments.
> [Fix #75] Fix a false negative for `Minitest/GlobalExpectations`

- .circleci/config.yml
- .rubocop.yml
- CHANGELOG.md
- rubocop-minitest.gemspec
- test/assertion_helper.rb
Follow https://github.com/rubocop-hq/rubocop/pull/7869.
> Drop support for Ruby 2.3

- Rakefile
- lib/rubocop/cop/generator.rb
To generate new cop
Like https://github.com/rubocop-hq/rubocop-rspec/blob/master/lib/rubocop/cop/rspec_cops.rb
> Add new_cops rake task

- CHANGELOG.md
- rubocop-minitest.gemspec
Follow up to https://github.com/rubocop-hq/rubocop-performance/issues/111.
This PR prepares to use RuboCop's new development API.
> Drop support for RuboCop 0.81 or lower

- CHANGELOG.md
- config/default.yml
- docs/modules/ROOT/pages/cops_minitest.adoc
- lib/rubocop/cop/minitest/assert_empty_literal.rb
- test/rubocop/cop/minitest/assert_empty_literal_test.rb
1. Added autocorrection
2. Also this cop was not implemented correctly as it should check against `assert_equal([], something)`, not `assert([], something)` - changed that
For reference: http://docs.seattlerb.org/minitest/Minitest/Assertions.html#method-i-assert
> Add autocorrect to `Rails/AssertEmptyLiteral` cop

- lib/rubocop/cop/minitest/multiple_assertions.rb
- lib/rubocop/cop/mixin/minitest_exploration_helpers.rb
- test/rubocop/cop/minitest/multiple_assertions_test.rb
This PR removes `MinitestExplorationHelpers#minitest_test_subclass` because For example, Rails testing does not inherit `Minitest::Test` directly but inherits `ActiveSupport::TestCase`.
A class that inherits some superclass and whose class name ends with `Test` is identified as a test class.
> Update `Minitest::Test` child check

- CHANGELOG.md
- lib/rubocop/cop/minitest/literal_as_actual_argument.rb
- lib/rubocop/cop/mixin/argument_range_helper.rb
- test/rubocop/cop/minitest/literal_as_actual_argument_test.rb
Fixes #101 and fixes #103. More info in those issues
> [Fix #101, #103] LiteralAsActualArgument parsing and autocorrect errors

- CHANGELOG.md
- rubocop-minitest.gemspec
RuboCop Minitest requires RuboCop 0.87 or higher due to use the new Autocorrection API.
https://github.com/rubocop-hq/rubocop/pull/7868
> Require RuboCop 0.87 or higher

- CHANGELOG.md
- lib/rubocop/cop/mixin/minitest_exploration_helpers.rb
- test/rubocop/cop/minitest/assert_output_test.rb
Fixes #106.
This PR fixes an error for `Minitest/AssertOutput` when using gvar at top level.
> [Fix #106] Fix an errof for `Minitest/AssertOutput` cop

- docs/modules/ROOT/pages/cops_minitest.adoc
- lib/rubocop/cop/minitest/refute_equal.rb
Use assert with a comparison instead of assert_equal. assert_equal takes 2
arguments, not 1 and both the next example and the bad examples below use
assert with a comparison.
> Fix assert typo in Minitest/RefuteEqual

- CHANGELOG.md
- lib/rubocop/cop/mixin/minitest_cop_rule.rb
- test/rubocop/cop/minitest/assert_equal_test.rb
Fixes #113.
This PR fixes an error for `Minitest/AssertEqual` and some cops when using `assert` with block argument.
> [Fix #113] Fix an error for `Minitest/AssertEqual`

- CHANGELOG.md
- docs/modules/ROOT/pages/cops_minitest.adoc
- lib/rubocop/cop/minitest/test_method_name.rb
- lib/rubocop/cop/mixin/minitest_exploration_helpers.rb
- test/rubocop/cop/minitest/test_method_name_test.rb
Fixes #115.
This PR fixes a false positive for `Minitest/TestMethodName` for when defining test method takes no arguments, and test method without assertion methods.
> [Fix #115] Fix a false positive for `Minitest/TestMethodName`

- Rakefile
In 2efa54df9ed2292eef89d8e5255f784de3c6f476 `VERSION` was changed to a module with a `STRING` constant but we forgot to update `bump_minor_version` in `Rakefile`. This bug prevents the `new_cop` Rake task from completing successfully.
> Access version correctly in `bump_minor_version`

- CHANGELOG.md
- docs/modules/ROOT/pages/cops_minitest.adoc
- lib/rubocop/cop/minitest/assert_empty_literal.rb
- test/rubocop/cop/minitest/assert_empty_literal_test.rb
While this cop is correct that we should be using `assert_empty(list)`
over `assert([], list)`, it's right for the wrong reasons. That example
is bad because it's using `assert` and not `assert_equal`. An empty
list/hash is truthy so the assertion will always succeed. That is,
`assert([], [1, 2, 3])` will succeed even though at a glance it looks
like it shouldn't. I believe that what this cop is intending to check
for is `assert_equal([], list)` instead so I've updated the references
to `assert` to `assert_equal`.
Issue #117 proposes that we try to detect when `assert` is used where
the user likely wanted `assert_equal` so while this cop will no longer
register a violation for `assert([], list)`, if that proposal is
accepted then a future cop *will* register a violation.
edit: #120 adds …
> Change `AssertEmptyLiteral` cop to check for `assert_equal`

- bin/console
The absence of the `yaml` require was preventing `bin/console` from
being able to execute. Requiring `pathname` doesn't seem to be necessary
but I threw it in too for good measure.
> Require `yaml` and `pathname` in `bin/console`

- CHANGELOG.md
- lib/rubocop/cop/minitest/test_method_name.rb
- test/rubocop/cop/minitest/test_method_name_test.rb
Currently it only works for tests with a single assertion.
> Fix `Minitest/TestMethodName` for tests with multiple assertions

- CHANGELOG.md
- lib/rubocop/cop/minitest/assert_empty_literal.rb
- lib/rubocop/cop/minitest/assert_in_delta.rb
- lib/rubocop/cop/minitest/assert_nil.rb
- lib/rubocop/cop/minitest/assert_path_exists.rb
- lib/rubocop/cop/minitest/assert_truthy.rb
- lib/rubocop/cop/minitest/global_expectations.rb
- lib/rubocop/cop/minitest/literal_as_actual_argument.rb
- lib/rubocop/cop/minitest/refute_equal.rb
- lib/rubocop/cop/minitest/refute_false.rb
- lib/rubocop/cop/minitest/refute_in_delta.rb
- lib/rubocop/cop/minitest/refute_nil.rb
- lib/rubocop/cop/minitest/refute_path_exists.rb
- lib/rubocop/cop/mixin/minitest_cop_rule.rb
- rubocop-minitest.gemspec
Follow https://github.com/rubocop-hq/rubocop/pull/8365
This PR uses `RESTRICT_ON_SEND` to restrict callbacks `on_send` to specific method names only.
`RESTRICT_ON_SEND` has been introduced since RuboCop 0.90.
> Require RuboCop 0.90 or higher due to use `RESTRICT_ON_SEND`

- .circleci/config.yml
- .rubocop.yml
- CHANGELOG.md
- rubocop-minitest.gemspec
- tasks/cops_documentation.rake
- test/assertion_helper.rb
Follow https://github.com/rubocop/rubocop/pull/9648.
> Drop Ruby 2.4 support

- CHANGELOG.md
- lib/rubocop/cop/mixin/minitest_exploration_helpers.rb
- test/rubocop/cop/minitest/multiple_assertions_test.rb
- test/rubocop/cop/minitest/no_assertions_test.rb
Fixes #131.
This PR fixes an error for `Minitest/MultipleAssertions` and fixes a false positive for `test` block.
Since RuboCop Minitest is a gem for Minitest, it should not support `ActiveSupport::TestCase` feature `test` block.
> [Fix #131] Fix an error for `Minitest/MultipleAssertions`

- CHANGELOG.md
- lib/rubocop/cop/minitest/multiple_assertions.rb
- lib/rubocop/cop/mixin/minitest_exploration_helpers.rb
- test/rubocop/cop/minitest/multiple_assertions_test.rb
- test/rubocop/cop/minitest/no_assertions_test.rb
Follow https://github.com/rubocop/rubocop-minitest/pull/132#issuecomment-828730794.
This PR supports Active Support's  method for `Minitest/MultipleAssertions` and `Minitest/NoAssertions` cops.
> Support Active Support's `test` method

- CHANGELOG.md
- lib/rubocop/cop/minitest/literal_as_actual_argument.rb
- test/rubocop/cop/minitest/literal_as_actual_argument_test.rb
Fixes #143.
This PR fixes an error for `Minitest/LiteralAsActualArgumentTest` when expected and actual arguments are literals.
> [Fix #143] Fix an error for `Minitest/LiteralAsActualArgumentTest`

- CHANGELOG.md
- config/default.yml
- docs/modules/ROOT/pages/cops_minitest.adoc
- lib/rubocop/cop/minitest/assert_empty_literal.rb
This PR marks `Minitest/AssertEmptyLiteral` as safe auto-correction.
Introduced as unsafe auto-correction in #85, but now safe auto-correction with changes in #118.
> Mark `Minitest/AssertEmptyLiteral` as safe auto-correction

- .rubocop_todo.yml
- CHANGELOG.md
- config/default.yml
- docs/modules/ROOT/pages/cops_minitest.adoc
- lib/rubocop/cop/minitest/global_expectations.rb
- test/rubocop/cop/minitest/global_expectations_test.rb
Add a new configuration value for Minitest/GlobalExpectations: EnforcedStyle.
This value sets the allowed and preferred method(s) with which to detect and
correct errors.
Fixes #147
> [Fix #147] Minitest/GlobalExpectations: add EnforcedStyle config value

- CHANGELOG.md
- lib/rubocop/cop/minitest/assert_empty.rb
- lib/rubocop/cop/minitest/refute_empty.rb
- test/rubocop/cop/minitest/assert_empty_test.rb
- test/rubocop/cop/minitest/refute_empty_test.rb
Fixes #150.
This PR fixes a false positive for `Minitest/AssertEmpty` and `RefuteEmpty` cops when using `empty` method with any arguments.
> [Fix #150] Fix a false positive for `Minitest/AssertEmpty` and `RefuteEmpty`

- .rubocop.yml
- rubocop-minitest.gemspec
Follows rubocop/rubocop#10239. Update gemspec to require MFA for privileged operations.
> Set `rubygems_mfa_required` in gemspec

- changelog/change_minitest_unreachable_assertion_aware_of_assertion_prefix_method.md
- lib/rubocop/cop/minitest/assertion_in_lifecycle_hook.rb
- lib/rubocop/cop/minitest/multiple_assertions.rb
- lib/rubocop/cop/minitest/no_assertions.rb
- lib/rubocop/cop/minitest/unreachable_assertion.rb
- lib/rubocop/cop/mixin/minitest_exploration_helpers.rb
This PR makes `Minitest/UnreachableAssertion` aware of `assert` and `refute` prefix methods and removes `MinitestExplorationHelpers#assertion?` method. It makes the detection to assertion methods consistent.
NOTE: The `MinitestExplorationHelpers#assertion?` method is redundant with `MinitestExplorationHelpers#assertion_method?` OTOH, the implementation uses
`MinitestExplorationHelpers#assertion` instead of `MinitestExplorationHelpers#assertion_method?`. Maybe it's enough to verify that it starts with `assert` or `refute` instead of exact match of the known assertion method names.
> Make `Minitest/UnreachableAssertion` aware of `assert` and `refute` prefix methods

- changelog/fix_false_positive_for_minitest_unreachable_assertion.md
- lib/rubocop/cop/minitest/unreachable_assertion.rb
- test/rubocop/cop/minitest/unreachable_assertion_test.rb
This PR fixes a false positive for `Minitest/UnreachableAssertion` when using only one assertion method in `assert_raises` block.
If `assert_raises` has only one assertion method, accept it considering the possibility of testing that assertion method.
> [Fix #159] Fix a false positive for `Minitest/UnreachableAssertion`

- changelog/change_make_assert_nil_aware_of_assert_predicate.md
- lib/rubocop/cop/minitest/assert_nil.rb
- lib/rubocop/cop/minitest/refute_nil.rb
- lib/rubocop/cop/mixin/nil_assertion_handleable.rb
- test/rubocop/cop/minitest/assert_nil_test.rb
- test/rubocop/cop/minitest/refute_nil_test.rb
This PR makes `Minitest/AssertNil` (`Minitest/RefuteNil`) aware of `assert_predicate(obj, :nil?)` (`refute_predicate(obj, :nil?)`).
Also tweak the redundant offense messages to simplify the implementation.
> Make `Minitest/AssertNil` aware of `assert_predicate`

- changelog/fix_missing_parents_in_duplicated_test_run_cop.md
- lib/rubocop/cop/minitest/duplicate_test_run.rb
- test/rubocop/cop/minitest/duplicate_test_run_test.rb
There's a slight logical error in the recent `DuplicateTestRun` addition.
Totally legit Ruby code can be marked as unparseable by this test:
```
parent_class_node = class_node_parent.each_child_node(:class).detect do |klass|
^^^^^^^^^^^^^^^^^
Did you mean?  class_node
/Users/gjtorikian/Development/rubocop-minitest/lib/rubocop/cop/minitest/duplicate_test_run.rb:69:in `parent_class_has_test_methods?'
/Users/gjtorikian/Development/rubocop-minitest/lib/rubocop/cop/minitest/duplicate_test_run.rb:56:in `on_class'
/Users/gjtorikian/.gem/bundler/gems/rubocop-2d3a972cb12b/lib/rubocop/cop/commissioner.rb:100:in `public_send'
/Users/gjtorikian/.gem/bundler/gems/rubocop-2d3a972cb12b/lib/rubocop/cop/commissioner.rb:100:in `block (2 levels) in trigger_responding_cops' …
```
> Protect against missing parents

- .circleci/config.yml
- .rubocop.yml
- changelog/change_drop_ruby_2_5_support.md
- rubocop-minitest.gemspec
Follow up https://github.com/rubocop/rubocop/pull/10577.
> Drop Ruby 2.5 support

- .github/ISSUE_TEMPLATE/feature_request.md
This pull request replaces RuboCop Rails with RuboCop Minitest in feature_request.md
> Replace RuboCop Rails with RuboCop Minitest in feature_request.md

- changelog/fix_a_false_positive_for_minitest_assert_predicate.md
- lib/rubocop/cop/mixin/predicate_assertion_handleable.rb
- test/rubocop/cop/minitest/assert_predicate_test.rb
- test/rubocop/cop/minitest/refute_predicate_test.rb
Fixes #172.
This PR fixes a false positive for `Minitest/AssertPredicate` and `Minitest/RefutePredicate` when using numbered parameters.
> [Fix #172] Fix a false positive for `Minitest/AssertPredicate`

- changelog/fix_raise_error_using_assert_with_block.md
- lib/rubocop/cop/mixin/predicate_assertion_handleable.rb
- test/rubocop/cop/minitest/assert_predicate_test.rb
rubocop-minitest was raising error if the style was to pass a block to an assert, such as power-assert.
So, I made it so that such cases are ignored.
This is stacktrace.
```
1) Error:
AssertPredicateTest#test_does_not_raise_error_using_assert_with_block:
NoMethodError: undefined method `block_type?' for nil:NilClass
return if first_argument.block_type? || first_argument.numblock_type?
^^^^^^^^^^^^
/Users/ippachi/ghq/github.com/ippachi/rubocop-minitest/lib/rubocop/cop/mixin/predicate_assertion_handleable.rb:16:in `on_send'
/Users/ippachi/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rubocop-f133b38b5893/lib/rubocop/cop/commissioner.rb:136:in `public_send'
/Users/ippachi/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rubocop-f133b38b5893/lib/rubocop/cop/commissioner. …
```
> Fix raise error when usgin assert with block

- changelog/fix_an_incorrect_autocorrect_for_minitest_assert_match.md
- lib/rubocop/cop/minitest/assert_match.rb
- lib/rubocop/cop/mixin/minitest_cop_rule.rb
- test/rubocop/cop/minitest/assert_match_test.rb
This PR fixes an incorrect autocorrect for `Minitest/AssertMatch` when `assert` with `match` and RHS is a regexp literal.
A regular expression literal must be the first argument to `assert_match`. `TypeError: no implicit conversion of Regexp into String` will occur if it is passed as the second argument.
```ruby
assert_match(object, /regexp/) #=> TypeError: no implicit conversion of Regexp into String
```
This issue was found on https://github.com/faker-ruby/faker/pull/2556.
> Fix an incorrect autocorrect for `Minitest/AssertMatch`

- changelog/fix_an_incorrect_autocorrect_for_minitest_refute_match.md
- lib/rubocop/cop/minitest/refute_match.rb
- test/rubocop/cop/minitest/refute_match_test.rb
Follow up #181 and #184.
This PR fixes an incorrect autocorrect for `Minitest/AssertMatch` when `refute` with `match` and RHS is a regexp literal.
A regular expression literal must be the first argument to `refute_match`. `TypeError: no implicit conversion of Regexp into String` will occur if it is passed as the second argument.
```ruby
refute_match(object, /regexp/) #=> TypeError: no implicit conversion of Regexp into String
```
> Fix an incorrect autocorrect for `Minitest/RefuteMatch`

- lib/rubocop/minitest/assert_offense.rb
Follow up https://github.com/rubocop/rubocop/pull/10987.
```console
% bundle exec rake
(snip)
NoMethodError: undefined method `disabled' for nil:NilClass
registry.disabled(config).each do |cop|
^^^^^^^^^
/Users/koic/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rubocop-479e588e16cd/lib/rubocop/comment_config.rb:94:in `inject_disabled_cops_directives'
/Users/koic/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rubocop-479e588e16cd/lib/rubocop/comment_config.rb:78:in `analyze'
/Users/koic/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/bundler/gems/rubocop-479e588e16cd/lib/rubocop/comment_config.rb:45:in `cop_disabled_line_ranges'
```
It supports multiple RuboCop core versions for compatibility with https://github.com/rubocop/rubocop-minitest/pull/156.
Before …
> Fix a build error

- changelog/fix_false_negative_for_minitest_empty_line_before_assertion_methods.md
- lib/rubocop/cop/minitest/empty_line_before_assertion_methods.rb
- test/project_test.rb
- test/rubocop/cop/minitest/empty_line_before_assertion_methods_test.rb
Fixes part of #189.
This PR fixes a false negative for `Minitest/EmptyLineBeforeAssertionMethods` when using non assertion method statement before assertion method used in a block.
> Fix a false negative for `Minitest/EmptyLineBeforeAssertionMethods`

- changelog/fix_a_false_positive_for_minitest_empty_line_before_assertion_methods.md
- lib/rubocop/cop/minitest/empty_line_before_assertion_methods.rb
- test/rubocop/cop/minitest/empty_line_before_assertion_methods_test.rb
Follow up https://github.com/rubocop/rubocop-minitest/issues/189#issuecomment-1298473301.
This PR fixes a false positive for `Minitest/EmptyLineBeforeAssertionMethods` when using `rescue` before assertion method.
> Fix a false positive for `Minitest/EmptyLineBeforeAssertionMethods`

- changelog/fix_false_positive_for_minitest_empty_line_before_assertion_methods.md
- lib/rubocop/cop/minitest/empty_line_before_assertion_methods.rb
- test/rubocop/cop/minitest/empty_line_before_assertion_methods_test.rb
Fixes #189 and #194.
This PR fixes a false negative for `Minitest/EmptyLineBeforeAssertionMethods` when using assertion method used in block before assertion method.
> [Fix #189] Fix a false positive for `Minitest/EmptyLineBeforeAssertionMethods`

- changelog/new_support_it_block.md
- lib/rubocop/cop/mixin/minitest_exploration_helpers.rb
- test/rubocop/cop/minitest/no_assertions_test.rb
Fixes #200.
This PR supports `it` testing block for minitest/spec.
`Minitest/GlobalExpectations` is already supported, so `it` testing block can also be supported by RuboCop Minitest.
> [Fix #200] Support `it` testing block for minitest/spec

- change_make_minitest_assert_with_expected_argument_aware_of_message_variable.md
- lib/rubocop/cop/minitest/assert_with_expected_argument.rb
- test/rubocop/cop/minitest/assert_with_expected_argument_test.rb
Fixes #206.
This PR makes `Minitest/AssertWithExpectedArgument` aware of message variable.
The second argument to the `assert` method named `message` and `msg` is allowed. Because their names are inferred as message arguments.
> [Fix #206] Make `Minitest/AssertWithExpectedArgument` aware of message variable

- changelog/change_mark_minitest_assert_truthy_as_unsafe_autocorrection.md
- config/default.yml
- lib/rubocop/cop/minitest/assert_truthy.rb
Fixes #209.
This PR marks `Minitest/AssertTruthy` as unsafe autocorrection.
> [Fix #209] Mark `Minitest/AssertTruthy` as unsafe autocorrection

- changelog/fix_a_false_positive_for_minitest_empty_line_before_assertion_methods.md
- lib/rubocop/cop/minitest/empty_line_before_assertion_methods.rb
- lib/rubocop/cop/mixin/minitest_exploration_helpers.rb
- test/rubocop/cop/minitest/empty_line_before_assertion_methods_test.rb
Fixes #210.
This PR fixes a false positive for `Minitest/EmptyLineBeforeAssertionMethodsTest` when using assertion method with block arg before other assertion method.
> [Fix #210] Fix a false positive for `Minitest/EmptyLineBeforeAssertionMethodsTest`

- changelog/change_raise_severity_of_some_cops_to_warning.md
- config/default.yml
The cops below belong to linting, not style preference, so make set the severity to warning.
The following emulates warnings for deprecated APIs:
- Minitest/GlobalExpectations (https://github.com/rubocop/rubocop-minitest/issues/60)
The following suggests incorrect usage of APIs:
- Minitest/AssertRaisesWithRegexpArgument:
- Minitest/AssertWithExpectedArgument:
- Minitest/SkipEnsure:
- Minitest/UnreachableAssertion:
> Raise severity of some cops to warning

- changelog/fix_an_error_for_minitest_test_file_name.md
- lib/rubocop/cop/minitest/test_file_name.rb
- test/rubocop/cop/minitest/test_file_name_test.rb
Fixes #225.
This PR fixes an error for `Minitest/TestFileName` when using empty file.
> [Fix #225] Fix an error for `Minitest/TestFileName`

- lib/rubocop/cop/minitest/test_method_name.rb
Removed method just duplicates the existing method from `MinitestExplorationHelpers` module.
I have seen similar patterns a few times at least in rubocop itself (for extracting methods; macros; methods and macros; class method nodes; etc from the class nodes), so wondering if its worth extracting it into `rubocop-ast` in the future.
> Remove duplication from `TestMethodName` cop

- changelog/change_what_is_considered_a_test_case.md
- lib/rubocop/cop/mixin/minitest_exploration_helpers.rb
- lib/rubocop/minitest/assert_offense.rb
- test/rubocop/cop/mixin/minitest_exploration_helpers_test.rb
While testing https://github.com/rubocop/rubocop-minitest/pull/229 on https://github.com/openstreetmap/openstreetmap-website, it detected this - https://github.com/openstreetmap/openstreetmap-website/blob/b278bc06ef720af8c21c99659c4d70334384c386/test/integration/oauth2_test.rb#L141, because `rubocop-minitest` detects all class methods starting with `test_` as test cases. But we should ignore such methods having arguments.
> Do not treat `test_` methods with arguments as test methods

- lib/rubocop/cop/minitest/multiple_assertions.rb
- lib/rubocop/cop/minitest/no_assertions.rb
- lib/rubocop/cop/mixin/minitest_exploration_helpers.rb
The method is duplicated in 2 places.
> Extract `#assertions_count`

- changelog/change_mark_minitest_refute_false_as_unsafe.md
- config/default.yml
- lib/rubocop/cop/minitest/refute_false.rb
Follow up https://github.com/rubocop/rubocop-minitest/issues/209#issuecomment-1385071429
This PR marks `Minitest/RefuteFalse` as unsafe. 
> Mark `Minitest/RefuteFalse` as unsafe

- changelog/change_mark_minitest_assert_truthy_as_unsafe.md
- config/default.yml
- lib/rubocop/cop/minitest/assert_truthy.rb
This PR marks `Minitest/AssertTruthy` as unsafe. As with #233, this is a false positive issue than autocorrection compatibility.
> Mark `Minitest/AssertTruthy` as unsafe

- changelog/fix_useless_assertion_for_commands.md
- lib/rubocop/cop/minitest/useless_assertion.rb
- test/rubocop/cop/minitest/useless_assertion_test.rb
Found a false positive: 
```ruby
assert_empty(`bundle exec yard --no-save --no-output --no-stats`)
```
https://github.com/fatkodima/sidekiq-iteration/blob/81453f8a5586367ba69c80aeea960fe824b76c40/test/documentation_test.rb#L8
> Fix a false positive for `Minitest/UselessAssertion` when using command execution

- changelog/new_accept_it_test_block_as_testcase.md
- lib/rubocop/cop/minitest/assert_output.rb
- lib/rubocop/cop/mixin/minitest_exploration_helpers.rb
- test/rubocop/cop/minitest/assert_output_test.rb
Follow up to https://github.com/rubocop/rubocop-minitest/pull/203.
That PR implemented support for `it`/`test` to be selected when selecting test cases, but the check for individual test cases (`test_case?` method) was missed to be extended.
> Support `it`/`test` testing blocks as test cases

- changelog/new_make_minitest_global_expectations_aware_of_pattern_matchers.md
- lib/rubocop/cop/minitest/global_expectations.rb
Follow up https://github.com/minitest/minitest/commit/0c44f4e
This PR makes `Minitest/GlobalExpectations` aware of `must_pattern_match` and `wont_pattern_match` matchers.
> Make `Minitest/GlobalExpectations` aware of pattern matchers

- changelog/fix_prevent_breaking_change_for_assertion_message_in_test.md
- lib/rubocop/minitest/assert_offense.rb
Follow up https://github.com/rubocop/rubocop/pull/11729.
This PR prevents breaking change for assertion message in test. e.g.
```console
% bundle exec ruby -Itest test/rubocop/cop/minitest/lifecycle_hooks_order_test.rb
(snip)
Fabulous run in 0.075080s, 93.2339 runs/s, 93.2339 assertions/s.
1) Failure:
LifecycleHooksOrderTest#test_registers_offense_when_hooks_are_not_before_test_cases [test/rubocop/cop/minitest/lifecycle_hooks_order_test.rb:62]:
--- expected
+++ actual
@@ -4,7 +4,7 @@
end
def setup; end
-  ^^^^^^^^^^^^^^ `setup` is supposed to appear before `test_something`.
+  ^^^^^^^^^^^^^^ Minitest/LifecycleHooksOrder: `setup` is supposed to appear before `test_something`.
def teardown; end
end
"
```
**Replace this text with a summary of the changes in your PR.
The more detailed you …
> Prevent breaking change for assertion message in test

- changelog/new_make_instance_of_cops_aware_of_equal.md
- lib/rubocop/cop/minitest/assert_instance_of.rb
- lib/rubocop/cop/minitest/refute_instance_of.rb
- lib/rubocop/cop/minitest_cops.rb
- lib/rubocop/cop/mixin/instance_of_assertion_handleable.rb
- test/rubocop/cop/minitest/assert_instance_of_test.rb
- test/rubocop/cop/minitest/refute_instance_of_test.rb
This PR makes `Minitest/AssertInstanceOf` and `Minitest/RefuteInstanceOf` aware of `assert_equal(Class, object.class)` and `refute_equal(Class, object.class)`.
> Make `Minitest/AssertInstanceOf` and `Minitest/RefuteInstanceOf` aware of `assert_equal` and `refute_equal`

- .circleci/config.yml
- .rubocop.yml
- changelog/change_drop_ruby_2_6_support.md
- lib/rubocop/minitest/assert_offense.rb
- rubocop-minitest.gemspec
- tasks/changelog.rb
- test/project_test.rb
Follow up https://github.com/rubocop/rubocop/pull/11791.
This PR drops Ruby 2.6 support. And JRuby has been dropped from the CI matrix because no JRuby-specific issues have been found and prevents the following build error:
```console
#!/bin/bash -eo pipefail
bundle install
Fetching https://github.com/rubocop/rubocop.git
You need to install git to be able to use gems from git repositories. For help
installing git, please refer to GitHub's tutorial at
https://help.github.com/articles/set-up-git
Exited with code exit status 11
CircleCI received exit code 11
```
https://app.circleci.com/pipelines/github/rubocop/rubocop-minitest/926/workflows/68776b54-5856-4acd-a99a-f41df114634d/jobs/6034
This does not mean no support for JRuby. RuboCop Minitest will continue to support JRuby 9.4+. …
> Drop Ruby 2.6 support

- changelog/change_handle_assertions_in_conditionals.md
- lib/rubocop/cop/minitest/multiple_assertions.rb
- lib/rubocop/cop/mixin/minitest_exploration_helpers.rb
- test/rubocop/cop/minitest/multiple_assertions_test.rb
These changes are to allow to have assertions like:
```ruby
def test_foo
if ActiveRecord::VERSION >= "7.0"
assert ActiveRecord.old_foo_method(1, 2)
else
assert ActiveRecord.new_foo_method(1, 2)
end 
end
```
A recent example that inspired this - https://github.com/ixti/sidekiq-throttled/pull/142/files#diff-87c291ea2af263111982285d3dea3083faa62260cc6080cc5396f4bf82a37cf4R22-R27 (it is using rspec, but it does not matter)
> Handle assertions in conditionals branches in `Minitest/MultipleAssertions` cop

- Gemfile
- Rakefile
https://github.com/tmm1/test-queue/pull/108 has been released, So RuboCop Minitest can be accelerated for testing by test-queue.
1.5x speedup in an environment:
```console
% bundle exec rake test
Run options: --seed 61017
(snip)
Fabulous run in 6.712563s, 348.0042 runs/s, 1010.7913 assertions/s.
2336 runs, 6785 assertions, 0 failures, 0 errors, 0 skips
```
```console
% bunlde exec rake test
Starting test-queue master (/tmp/test_queue_12114_1480.sock)
==> Summary (16 workers in 4.2143s)
[ 1]      470 runs, 900 assertions, 0 failures, 0 errors, 0 skips         1 suites in 4.2041s      (pid 12117 exit 0 )
[ 2]      470 runs, 820 assertions, 0 failures, 0 errors, 0 skips         1 suites in 4.2043s      (pid 12118 exit 0 )
[ 3]        81 runs, 81 assertions, 0 failures, 0 errors, 0 skips …
```
> Use test-queue

- changelog/fix_a_false_positive_for_minitest_refute_equal.md
- lib/rubocop/cop/minitest/refute_equal.rb
- test/rubocop/cop/minitest/refute_equal_test.rb
Fixes #256.
This PR fixes a false positive for `Minitest/RefuteEqual` when `assert(!expected == actual)`.
> [Fix #256] Fix a false positive for `Minitest/RefuteEqual`

- changelog/fix_an_error_for_assert_operator.md
- lib/rubocop/cop/minitest/assert_operator.rb
- lib/rubocop/cop/minitest/refute_operator.rb
- test/rubocop/cop/minitest/assert_operator_test.rb
- test/rubocop/cop/minitest/refute_operator_test.rb
Fixes #261.
This PR fixes an error for `Minitest/AssertOperator` and `Minitest/RefuteOperator` when using variable argument.
> [Fix #261] Fix an error for `Minitest/AssertOperator`

- lib/rubocop/cop/minitest/assert_operator.rb
- lib/rubocop/cop/minitest/refute_operator.rb
- test/rubocop/cop/minitest/assert_operator_test.rb
- test/rubocop/cop/minitest/refute_operator_test.rb
Update the `AssertOperator` and `RefuteOperator` cops to allow `:[]`
The rubocop style guide prefers `assert` and `refute` for testing booleans. If I have an array of booleans, then I want to be able to use this style:
```
def test_my_array
assert(array_of_bools[0])
refute(array_of_bools[1])
end
```
This PR is suggested by an [actual test in the Nokogiri suite](https://github.com/sparklemotion/nokogiri/blob/main/test/xml/test_reader.rb#L699-L700) which collects boolean values from Nokogiri::Reader as it passes through the document, and then checks the values after completing the parsing pass. That test could be rewritten, but I don't personally think it would be made more readable by that rewrite.
Also see https://github.com/rubocop/rubocop-minitest/pull/260#issuecomment-1734520785 which …
> Update AssertOperator and RefuteOperator to allow :[]

- changelog/fix_an_error_for_assert_operator_and_refute_operator.md
- lib/rubocop/cop/minitest/assert_operator.rb
- lib/rubocop/cop/minitest/refute_operator.rb
- test/rubocop/cop/minitest/assert_operator_test.rb
- test/rubocop/cop/minitest/refute_operator_test.rb
This PR fixes an error for `Minitest/AssertOperator` and `Minitest/RefuteOperator` when using unary operation argument.
> Fix an error for `Minitest/AssertOperator` and `Minitest/RefuteOperator`

- changelog/new_make_minitest_assert_equal_aware_of_assert_operator.md
- lib/rubocop/cop/minitest/assert_equal.rb
- test/rubocop/cop/minitest/assert_equal_test.rb
This PR makes `Minitest/AssertEqual` aware of `assert_operator`.
> Make `Minitest/AssertEqual` aware of `assert_operator`

- changelog/new_make_minitest_refute_equal_aware_of_assert_operator_and_refute_operator.md
- lib/rubocop/cop/minitest/refute_equal.rb
- test/rubocop/cop/minitest/refute_equal_test.rb
This PR makes `Minitest/RefuteEqual` aware of `assert_operator` and `refute_operator`.
> Make `Minitest/RefuteEqual` aware of `assert_operator` and `refute_operator`

- changelog/new_make_minitest_assert_match_aware_of_assert_operator.md
- lib/rubocop/cop/minitest/assert_match.rb
- lib/rubocop/cop/minitest/refute_match.rb
- test/rubocop/cop/minitest/assert_match_test.rb
This PR makes `Minitest/AssertMatch` aware of `assert_operator`.
> Make `Minitest/AssertMatch` aware of `assert_operator`

- changelog/new_make_minitest_refute_match_aware_of_refute_operator.md
- lib/rubocop/cop/minitest/refute_match.rb
- test/rubocop/cop/minitest/refute_match_test.rb
This PR makes `Minitest/RefuteMatch` aware of `refute_operator` and `assert_operator`.
> Make `Minitest/RefuteMatch` aware of `refute_operator`

- changelog/change_ignore_offenses_inside_redundant.md
- lib/rubocop/cop/minitest/assert_empty.rb
- lib/rubocop/cop/minitest/refute_empty.rb
- lib/rubocop/cop/mixin/minitest_cop_rule.rb
- lib/rubocop/cop/mixin/predicate_assertion_handleable.rb
- test/rubocop/cop/minitest/assert_empty_test.rb
- test/rubocop/cop/minitest/assert_includes_test.rb
- test/rubocop/cop/minitest/assert_predicate_test.rb
- test/rubocop/cop/minitest/assert_respond_to_test.rb
- test/rubocop/cop/minitest/refute_empty_test.rb
- test/rubocop/cop/minitest/refute_includes_test.rb
- test/rubocop/cop/minitest/refute_match_test.rb
- test/rubocop/cop/minitest/refute_predicate_test.rb
- test/rubocop/cop/minitest/refute_respond_to_test.rb
rubocop/rubocop#11739 updated `Style/RedundantParentheses` to detect this, so we can now consider it out of scope of these cops, as was done in https://github.com/rubocop/rubocop-minitest/pull/248/files#r1150046949.
* ~Commit message starts with `[Fix #issue-number]` (if the related issue exists).~
> Ignore offenses inside redundant parentheses

- changelog/fix_false_positive_for_empty_line_before_assertion_methods_and_assert_raises.md
- lib/rubocop/cop/mixin/minitest_exploration_helpers.rb
- test/rubocop/cop/minitest/empty_line_before_assertion_methods_test.rb
> Fix a false positive for `Minitest/EmptyLineBeforeAssertionMethods` and `assert_raises`

- changelog/change_require_rubocop_ast_1_30.md
- lib/rubocop/cop/minitest/assert_empty.rb
- lib/rubocop/cop/minitest/empty_line_before_assertion_methods.rb
- lib/rubocop/cop/minitest/refute_empty.rb
- lib/rubocop/cop/mixin/argument_range_helper.rb
- rubocop-minitest.gemspec
Follow up https://github.com/rubocop/rubocop/pull/12305.
> Require RuboCop AST 1.30.0+

- .github/workflows/test.yml
- changelog/fix_error_for_minitest_assert_operator_and_refute_operator.md
- lib/rubocop/cop/minitest/assert_operator.rb
- lib/rubocop/cop/minitest/refute_operator.rb
This PR fixes the following error for `Minitst/AssertOperator` and `Minitest/RefuteOperator`
when running with Ruby 2.7:
```console
$ ruby -v
ruby 2.7.8p225 (2023-03-30 revision 1f4d455848) [x86_64-darwin19]
$ bundle exec rake
Finished in 2.522134s, 15.0666 runs/s, 18.6350 assertions/s.
1) Error: RefuteOperatorTest#test_registers_offense_when_using_refute_with_operator_method_and_message:
FrozenError: can't modify frozen String: "expected, :<, actual"
/Users/koic/src/github.com/rubocop/rubocop-minitest/lib/rubocop/cop/minitest/refute_operator.rb:46:
in `build_new_arguments'
/Users/koic/src/github.com/rubocop/rubocop-minitest/lib/rubocop/cop/minitest/refute_operator.rb:30:
in `on_send'
```
And it introduces CI for the oldest RuboCop version still supported, implementing a workflow for …
> Fix an error for `Minitst/AssertOperator` and `Minitest/RefuteOperator`

- changelog/change_assert_same_check_object_ids.md
- lib/rubocop/cop/minitest/assert_same.rb
- lib/rubocop/cop/minitest/refute_same.rb
- test/rubocop/cop/minitest/assert_same_test.rb
- test/rubocop/cop/minitest/refute_same_test.rb
It is a very popular pattern:
```ruby
assert_equal(expected.object_id, actual.object_id)
assert_same(expected, actual)
```
Tested on `rails/rails` codebase and got 11 offenses.
> Enhance `AssertSame`/`RefuteSame` to check for `object_id` comparison

- changelog/fix_an_error_when_using_assigning_a_value_to_an_object_attribute.md
- lib/rubocop/cop/mixin/minitest_exploration_helpers.rb
- test/rubocop/cop/minitest/multiple_assertions_test.rb
Fixes #281.
This PR fixes an error when assigning a value to an object attribute.
> [Fix #281] Fix an error when assigning a value to an object attribute

- changelog/fix_an_error_for_minitest_multiple_assertions.md
- lib/rubocop/cop/mixin/minitest_exploration_helpers.rb
- test/rubocop/cop/minitest/multiple_assertions_test.rb
Fixes #283.
This PR fixes an error for `Minitest/MultipleAssertions` when using `||` assigning a value to a variable.
> [Fix #283] Fix an error for `Minitest/MultipleAssertions`

- changelog/fix_don_t_error_on_empty_blocks_when_linting.md
- lib/rubocop/cop/minitest/assert_raises_compound_body.rb
- test/rubocop/cop/minitest/assert_raises_compound_body_test.rb
Fixes #287
This fixes `Minitest/AssertRaisesCompoundBody` erroring on empty blocks
> [Fix #287] don't error on empty blocks when linting `assert_raises`

- changelog/fix_don_t_count_assertions_twice_when_their.md
- lib/rubocop/cop/minitest/multiple_assertions.rb
- test/rubocop/cop/minitest/multiple_assertions_test.rb
Fixes #289
This fixes `Minitest/MultipleAssertions` counting assertions twice when their return value is being assigned
> [Fix #289] don't count assertions twice when their return value is being assigned

- lib/rubocop/cop/minitest/multiple_assertions.rb
- test/rubocop/cop/minitest/multiple_assertions_test.rb
Follow up to #290 / #289 - I realised when re-reviewing my change that `assertion_method?` only checks the immediate expression of assignments, which makes sense for what it's meant to be doing - so we need to still handle checking the bodies of blocks for assignments.
I've not added a changelog for this since the original PR has not been released so I figured it would still be considered a single "fix", but let me know if you'd still like a second changelog entry anyway.
> [Fix #289] count asserts within blocks for assignments

- .github/workflows/test.yml
- Rakefile
- tasks/changelog.rake
I realised while working on my recent PRs that CI wasn't actually failing when `bundle exec rake [test]` reported errors - turns out that tests are being invoked by `system` which by default does not do any error handling; instead it sets `$?` to the exit code which can then be checked.
Ruby 2.6 added an `exception` option which when `true` causes `system` to raise an exception if the command exits with a non-zero code, making this very easy to address.
I've checked the codebase and confirmed these are the only uses of `system`.
> Raise an exception if tests or changelog generation fails

- .github/workflows/test.yml
- Rakefile
Follow up to #294
Currently this is aimed at being the most straightforward if probably slightly inelegant way to get tests running on JRuby - I assume there is probably a slightly cleaner way of invoking tests but I don't yet know what it is and `Rake::TestTask` was more than a few lines of code 😅
I think it would be worth considering having `test-queue` "support" JRuby by not using `fork` if that platform is detected or if you set `TEST_QUEUE_WORKERS` to 1 (or maybe 0?) as a way of making it easier to have a normalized way of invoking tests across different platforms like this; but it would also be equally valid I think for `test-queue` to say that's out of scope for the gem🤷 
[1]: …
> Don't use `test-queue` to run tests on JRuby because it doesn't support `fork`

- changelog/fix_ensure_all_kinds_of_assignments_are.md
- lib/rubocop/cop/minitest/multiple_assertions.rb
- test/rubocop/cop/minitest/multiple_assertions_test.rb
Fixes #292
Fixes #295
This ensures that `Minitest/MultipleAssertions` properly counts assertions when dealing with assignments - I expect (and hope) this is pretty rare in real-world code, but it is technically correct for the cop to be doing and the actual support isn't that complex.
I've only added a single test to ensure all the types of assignment work, and then a test using the standard assignment operator for each different kind of complex node (block, if, rescue, etc) since they all work the same except for mass assignment and it would be very tedious to write all those tests; they could be done through loops but I'm not sure its worth it vs the complexity.
Speaking of mass assignment, that is the fly in the ointment - I've added support for single method and array, and then had it …
> [Fix #292] ensure all kinds of assignments are correctly handled when counting assertions

- changelog/change_AssertKindOf_is_a.md
- config/default.yml
- lib/rubocop/cop/minitest/assert_kind_of.rb
- lib/rubocop/cop/minitest/refute_kind_of.rb
- test/rubocop/cop/minitest/assert_kind_of_test.rb
- test/rubocop/cop/minitest/refute_kind_of_test.rb
The [`Minitest/AssertKindOf`](https://docs.rubocop.org/rubocop-minitest/cops_minitest.html#minitestassertkindof) would replace this code:
```ruby
assert(object.kind_of?(Class))
```
... but not:
```ruby
assert(object.is_a?(Class))
```
...even though they are practically the same, since [`#is_a?`](https://ruby-doc.org/3.2.2/Object.html#method-i-is_a-3F) is an alias for [`#kind_of?`](https://ruby-doc.org/3.2.2/Object.html#method-i-kind_of-3F) (not to be confused with [`#instance_of?`](https://ruby-doc.org/3.2.2/Object.html#method-i-instance_of-3F)).
This PR simply extends `Minitest/AssertKindOf` to correct both.
I opted to modify the existing cop, rather than introducing a new cop like `Minitest/AssertIsA`, because it seems really unlikely to me that somebody would like to correct one, but …
> `AssertKindOf`: also replace `is_a?` as well

- changelog/fix_an_error_for_style_useless_assertion.md
- lib/rubocop/cop/minitest/useless_assertion.rb
- test/rubocop/cop/minitest/useless_assertion_test.rb
This fixes an error for the followng code snippet:
```rb
assert_equal(1)
```
The code is broken and doesn't work but if using rubocop in lsp mode something that a user can type momentarily.
> Fix an error for `Style/UselessAssertion` when passing a single argument to methods to accept two arguments

- changelog/fix_an_error_for_assert_empty_literal.md
- lib/rubocop/cop/minitest/assert_empty_literal.rb
- test/rubocop/cop/minitest/assert_empty_literal_test.rb
Another error that is more likely to occur while running RuboCop in LSP mode.
> Fix an error for `Minitest/AssertEmptyLiteral` when only passing an empty literal

- .github/workflows/test.yml
- changelog/change_require_rubocop_1_61.md
- config/default.yml
- rubocop-minitest.gemspec
Follow up https://github.com/rubocop/rubocop-minitest/pull/302#issuecomment-1945308338.
This PR updates the dependency version to RuboCop 1.61, which supports `AutoCorrect: contextual`, and updates `Minitest/Focus`'s config.
https://github.com/rubocop/rubocop/releases/tag/v1.61.0
> Require RuboCop 1.61 to use `AutoCorrect: Contextual`

- .github/workflows/test.yml
- Rakefile
- test/rubocop/cop/minitest/multiple_assertions_test.rb
The shared `@cop` instance variable of `AssertOffense` module causes flaky tests due to state changes.
The `AssertOffense` testing module needs to be updated to allow for tests that are independent in configuration between tests. It is necessary to prevent race conditions caused by shared configurations.
This is a workaround to skip tests until the issue is resolved in the `AssertOffense` module.
> Fix flaky testing for `Minitst/MultipleAssertions`

- .github/workflows/test.yml
- Gemfile
- Rakefile
- changelog/change_support_prism.md
- lib/rubocop/minitest/assert_offense.rb
- rubocop-minitest.gemspec
Follow up https://github.com/rubocop/rubocop-ast/pull/277
There are no changes to the implementation, but the required dependency version of RuboCop AST will be updated. It would be more rational than adding new dependency on `gem 'rubocop-ast', '>= 1.31.1'` in the Gemfile just to bump up the minor version.
RuboCop Minitest now ensures that `RuboCop::AST::ProcessedSource` used in tests is aware of `parser_engine` parameter.
Tests for RuboCop AST with Prism as the backend can be run as follows:
```console
bundle exec rake prism_test
```
The above is the shortcut alias for:
```console
PARSER_ENGINE=parser_prism bundle exec rake test
```
RuboCop works on Ruby versions 2.7+, but since Prism only targets parsing for Ruby 3.3+, `internal_investigation` Rake task will not be executed. This task …
> Support Prism as a Ruby parser

- lib/rubocop/minitest/assert_offense.rb
The minimal supported version is currently 1.61. This condition is not needed anymore
> Remove a workaround for older RuboCop versions

- changelog/new_support_no_corrections.md
- lib/rubocop/minitest/assert_offense.rb
Despite being mentioned in the `AssertOffense` documentation, `assert_no_corrections` was not supported: https://github.com/rubocop/rubocop-minitest/blob/v0.35.0/lib/rubocop/minitest/assert_offense.rb#L58-L72
This PR makes `assert_no_corrections` supported in accordance with the documentation.
> Make `AssertOffense` support `assert_no_corrections`

- changelog/fix_suppress_deprecation_warning_for_minitest_multiple_assertions.md
- lib/rubocop/cop/minitest/multiple_assertions.rb
Follow up https://github.com/rubocop/rubocop/pull/13032 and https://github.com/rubocop/rubocop/pull/9471.
This PR suppresses deprecation warning for `Minitst/MultipleAssertions`.
> Suppress deprecation warning for `Minitst/MultipleAssertions`

- changelog/change_assert_offense_setup_fails_with_useful_message.md
- lib/rubocop/minitest/assert_offense.rb
- test/rubocop/cop/minitest/assert_offense_test.rb
- test/rubocop/cop/minitest/test_file_name_test.rb
Including the `AssertOffense` module currently fails with a cryptic message if the cop can't be found. This PR introduces an explicit failure with a useful message, replacing the `NoMethodError` that is currently raised in this situation.
**Before**
```
Error:
RuboCop::Cop::MyCops::MyNewCopTest#test_works:
NoMethodError: undefined method `[]=' for nil
/Users/brandoncc/.gem/ruby/3.3.1/gems/rubocop-minitest-0.35.1/lib/rubocop/minitest/assert_offense.rb:109:in `assert_offense'
test/rubocop/cop/my_cops/my_new_cop_test.rb:12:in `block in <class:MyNewCopTest>'
```
**After**
```
Error:
RuboCop::Cop::MyCops::MyNewCopTest#test_works:
RuntimeError: Cop not defined: RuboCop::Cop::MyCops::MyNewCop
/Users/brandoncc/dev/rubocop-minitest/lib/rubocop/minitest/assert_offense.rb:81:in `cop' …
```
> Tests using AssertOffense should Fail with a usable message if the relevant cop is not defined

- changelog/fix_error_skip_ensure.md
- lib/rubocop/cop/minitest/skip_ensure.rb
- test/rubocop/cop/minitest/skip_ensure_test.rb
Found at https://github.com/Shopify/shopify_app/blob/1dda5cb5642e34338961cc65d8069455e568e162/test/shopify_app/controller_concerns/token_exchange_test.rb#L30-L35
> Fix an error for `Minitest/SkipEnsure` when only `ensure` has a body

- changelog/fix_error_multiple_assertions.md
- lib/rubocop/cop/minitest/multiple_assertions.rb
- test/rubocop/cop/minitest/multiple_assertions_test.rb
They produce an assign node, but the value is part of the parent for node.
I noticed there are some flaky tests in that file being skipped. I enabled them locally, and they pass with this change.
> Fix an error for `Minitest/MultipleAssertions` when using for-style loops

- test/rubocop/cop/minitest/multiple_assertions_test.rb
`MultipleAssertionsTest#test_all_types_of_assignments_are_understood [test/rubocop/cop/minitest/multiple_assertions_test.rb:131]` is failing in master.
> Fix broken test in master

- lib/rubocop/cop/minitest/skip_ensure.rb
- rubocop-minitest.gemspec
`EnsureNode.body` has been deprecated in rubocop/rubocop-ast#337, and will be reimplemented in the next major version of rubocop-ast. In order to prepare for that, existing `EnsureNode.body` calls, which retreive the `ensure` branch of exception handling, have been replaced with `EnsureNode.branch`.
> Replace `EnsureNode.body` with `EnsureNode.branch`

- test/rubocop/cop/minitest/multiple_assertions_test.rb
The following test passed with Prism 1.2.0, but started failing with Prism 1.3.0.
```console
$ bundle exec rake prism_test
(snip)
==> Failures
1) Failure:
MultipleAssertionsTest#test_assignments_with_numblocks_are_counted_correctly [test/rubocop/cop/minitest/multiple_assertions_test.rb:244]:
--- expected
+++ actual
@@ -1,6 +1,5 @@
"class FooTest < ActiveSupport::TestCase
test \"#render errors include stack traces\" do
-  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Test case has too many assertions [9/1].
err = assert_raises React::ServerRendering::PrerenderError do
assert_equal _1, 1
```
> Workaround for a build error with Prism 1.3.0

- changelog/change_load_less_of_minitest_in_the_test.md
- lib/rubocop/minitest/support.rb
- test/test_helper.rb
Allow other projects to load "rubocop/minitest/support" without opting in to "minitest/autorun" and 'minitest/pride'.
> Load less of minitest in the test support file

- .github/workflows/test.yml
- changelog/fix_require_rubocop_version_for_plugin.md
- rubocop-minitest.gemspec
RuboCop 1.72 or later is required for plugin support.
> Update `add_dependency` of RuboCop to 1.72 for plugin support

- .github/workflows/test.yml
- changelog/new_support_itblock_in_minitest_cops.md
- lib/rubocop/cop/minitest/multiple_assertions.rb
- lib/rubocop/minitest/assert_offense.rb
- rubocop-minitest.gemspec
- test/rubocop/cop/minitest/assert_predicate_test.rb
- test/rubocop/cop/minitest/multiple_assertions_test.rb
- test/rubocop/cop/minitest/refute_predicate_test.rb
- test/rubocop/cop/minitest/return_in_test_case_method_test.rb
This PR supports `it` block parameter in `Minitest` cops.
> Support `it` block parameter in `Minitest` cops

- changelog/fix_false_positives_for_minitest_no_assertion_test.md
- lib/rubocop/cop/minitest/global_expectations.rb
- lib/rubocop/cop/minitest/no_assertions.rb
- lib/rubocop/cop/mixin/minitest_exploration_helpers.rb
- test/rubocop/cop/minitest/no_assertions_test.rb
This PR fixes false positives for `Minitest/NoAssertions` when using matcher methods.
Resolves #332
> [Fix #332] Fix false positives for `Minitest/NoAssertions`
